[package]
name = "game_of_tag"
version = "0.1.0"
authors = ["Liam Clancy (metafeather)"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
